http:
  port: ':8080'
  timeout: '30s'
  shutdown_timeout: '15s'
  read_timeout: '15s'
  write_timeout: '60s'

db:
  host: 'postgres'
  port: '5432'
  db_name: 'ustaz_hub_db'
  username: 'postgres'

token:
  time_to_live: "15m"